### ISSUE TITLE
Black screen with HDMI and vsync_adjust=2

### ISSUE THREAD

**Issue by bootsector** [MrX-8B/MiSTer-Arcade-GreenBeret#1] opened 2019-11-05 11:45 UTC
I get a black screen on my HDMI display with the following setting in MiSTer.ini:

vsync_adjust=2

All other cores seem to work fine with this setting.

**Comment by MrX-8B** [comment] 2019-11-05 11:49
Thank you for your report.
V-Sync frequency seems to be slightly faster.
This will be fixed in a few days.

**Comment by bootsector** [comment] 2019-11-05 11:50
You rock! Thank you for making these awesome cores for the MiSTer community!

**Comment by MrX-8B** [comment] 2019-11-06 10:36
Corrected the frequency of V-Sync.
I confirmed it was 60.6Hz on my HDMI monitor.

When you are sure that it works, close the issue.

**Comment by bootsector** [comment] 2019-11-06 10:37
Awesome! I will test this and report tonight, when I get home! You rock!!!

**Comment by bootsector** [comment] 2019-11-06 21:06
It still black screens for me! :thinking:

**Comment by MrX-8B** [comment] 2019-11-07 00:54
Hmm... Why could? 🤔
It's a confirmation, but it's not a problem with the other cores I made, right?
(Dig Dug, Gaplus, Ninja-Kun etc.)

**Comment by bootsector** [comment] 2019-11-07 06:13
Ninja-Kun -> Works!
Gaplus -> Doesn't work!

**Comment by MrX-8B** [comment] 2019-11-07 07:59
I understood. Thank you.

If Gaplus doesn't appear on the screen, it can be difficult to fix.
This seems to be a problem that depends on the HDMI monitor you are using.
Even if it can be displayed on the screen, the refresh rate will change from the actual machine.

If that's ok, you can fix this problem.
Can you build the core from the source code?
If possible, I'll tell you the settings, so build your own core that you've modified to appear on the screen.

**Comment by bootsector** [comment] 2019-11-07 10:46
Thanks for replying back! So if I understood correctly, core is running with the original video frequency now, right? if that's the case, it just makes sense to me to set vsync_adjust=0 or 1, since it's my display that is having issues with the original frequency. Let me know so I can close this! Thank you!

**Comment by MrX-8B** [comment] 2019-11-07 21:37
You are right in understanding.
This issue will be closed.
Thank you.

**Closed as completed by MrX-8B** 2019-11-07 21:37 UTC
